"""Domain protocols (interfaces) for The Spillover Engine.

These define the contracts that adapters and engine components must satisfy.
All protocols are runtime-checkable for adapter validation at registration time.

pandas is imported only under TYPE_CHECKING to keep the domain layer free of
heavyweight runtime dependencies.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    import pandas as pd

from .value_objects import PolicyName


@runtime_checkable
class SpilloverPolicy(Protocol):
    """Contract for a policy that computes FB/EB45 savings and adjusts India EB-1 supply."""

    name: PolicyName

    def compute_fb_savings(self, dos_df: pd.DataFrame) -> int:
        """Return FB visa savings generated by this policy."""
        ...

    def compute_eb45_savings(self, dos_df: pd.DataFrame) -> int:
        """Return EB-4/5 visa savings generated by this policy."""
        ...

    def adjust_india_eb1_supply(
        self,
        base_india_supply: int,
        fb_savings: int,
        eb45_savings: int,
        total_eb1_supply: int,
        dos_df: pd.DataFrame,
    ) -> int:
        """Return adjusted India EB-1 supply after applying this policy."""
        ...


@runtime_checkable
class DOSDataLoader(Protocol):
    """Contract for loading consolidated DOS IV issuance data."""

    def load_all_issuances(self) -> pd.DataFrame:
        """Load and return all DOS issuance records as a single DataFrame."""
        ...


@runtime_checkable
class Parser(Protocol):
    """Contract for a generic data parser."""

    def parse(self) -> pd.DataFrame:
        """Parse the underlying data source and return a DataFrame."""
        ...
